### ISSUE TITLE
Building app against demandlib cause file-not-found error

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#110]
Recently I started to built an app against the demandlib API. Executing this app from a location other than <somewhere>/oemof/examples/ raises an error. Problem is that the `selp_series.csv` is not found cause by relative path definition in oemof-demandlib.

```
guido@pc-12:~/home/git-repos/app_demand$ ./eGo_app_demand.py random
Traceback (most recent call last):
  File "./eGo_app_demand.py", line 91, in <module>
    calculate_slp(args.mode, args.schema, args.table)
  File "./eGo_app_demand.py", line 57, in calculate_slp
    'selp_type': 'i0'}])
  File "/home/guido/home/git-repos/oemof/oemof/tools/helpers.py", line 493, in call_demandlib
    'comm_number_of_employees_region')).elec_demand
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/demand.py", line 148, in __init__
    self.decider(method, **kwargs)
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/demand.py", line 173, in decider
    self.e_slp = self.read_selp().slp
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/demand.py", line 239, in read_selp
    self.e_slp = eb.bdew_elec_slp(self.conn, self.dataframe)
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/energy_buildings.py", line 194, in __init__
    self.slp_frame = self.all_load_profiles(conn, time_df)
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/energy_buildings.py", line 199, in all_load_profiles
    new_df = self.create_bdew_load_profiles(time_df, slp_types)
  File "/home/guido/home/git-repos/oemof/oemof/demandlib/energy_buildings.py", line 216, in create_bdew_load_profiles
    selp_series = pd.read_csv('../oemof/demandlib/selp_series.csv')
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 275, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 590, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 731, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1103, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
OSError: File b'../oemof/demandlib/selp_series.csv' does not exist
```

Spontaneously I would suggest keeping such files in the oemof-path (`~/.oemof/`) and create a method/ function that retrieves this file from the vernetzen-server as @uvchik has done before in an other example.

**Comment by simonhilpert** [comment]
interestingly, I am cleaning up the demand lib heat part at the moment to do something similar (?). depends on what your building app is supposed to to.  maybe we should get in touch?

**Comment by gplssm** [comment]
oh yeah - i like getting in touch! ;)

currently I'm doing demand time series data creation in context of the open_eGo project. shall we have a phone call later on?

**Comment by simonhilpert** [comment]
13:30?

**Comment by gplssm** [comment]
Perfectly fine!

If we are on the way, let's discuss this issue too #77 

I call ya!

**Comment by simonhilpert** [comment]
k

**Comment by gplssm** [comment]
The issue is resolved in the branch features/cleanup-demandlib by f9c62a4899bd51c051e44a8b7c69f9becca56d84
