### ISSUE TITLE
bdew heat profile shlp -type 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#126]
I tried to run the heatprofile calculation with the bdew equations. Using 'shlp_type'=MFH causes an error. 
Can someone of you check @uvchik @birgits ? 

Can you reproduce the error? 

```python 
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/home/simon/znes/projects/oemof/oemof_base/oemof/demandlib/bdew_heatprofile.py", line 229, in create_bdew_profile
    KW = annual_heat_demand / (sum(h * F) / 24)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/ops.py", line 618, in wrapper
    return left._constructor(wrap_results(na_op(lvalues, rvalues)),
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/ops.py", line 553, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pandas/computation/expressions.py", line 218, in evaluate
    **eval_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pandas/computation/expressions.py", line 129, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b, raise_on_error)
  File "/usr/local/lib/python3.4/dist-packages/pandas/computation/expressions.py", line 71, in _evaluate_standard
    return op(a, b)
ValueError: operands could not be broadcast together with shapes (8760,) (8767,) 
```

**Comment by simnh** [comment]
Maybe it's located inside the provided csv-files?

**Comment by uvchik** [comment]
I need the call to reproduce the error.

**Comment by simnh** [comment]
can you just try to call the heat_demand_example.py in the development examples 

replace 'EFH' with 'MFH' will cause an error....

```python
efh.heat_load = efh.hourly_heat_demand(fun=bdew_heat.create_bdew_profile,
                                       datapath="../../oemof/demandlib/bdew_data",
                                       year=2010, holidays=holidays,
                                       temperature=temperature,
                                       shlp_type='EFH',
                                       building_class=1,
                                       wind_class=1,
                                       annual_heat_demand=25000)
```

**Comment by uvchik** [comment]
Fixed with commit b4e86806 and merged into dev. I think it was fast enough to be part of the March release.

**Comment by uvchik** [comment]
Sorry I think the workflow is, that I have to reassign it to you (@simnh) and you can close the issue if everything works for you.

**Comment by simnh** [comment]
ok works for me! (i don't get an error)..
Thx!!!
