### ISSUE TITLE
Nested energy systems

### ISSUE THREAD

**Issue by Jazzpilz** [oemof/oemof#166]
I tried out nesting energy systems, but get an KeyError of pyomo:

-----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frederik/Dokumente/Ausbildung/GSoC/Project/tests/general/Structure/mwe_merging2hubs_nested.py", line 33, in <module>
    sys1.optimize()
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/core/energy_system.py", line 238, in optimize
    om = OM(energysystem=self)
  File "/home/frederik/anacond
KeyError: "Error accessing indexed component: Index '('transport_bel1_1bel1', 'bel1_1', 2773)' is not valid for array component 'w'"a3/lib/python3.5/site-packages/oemof/solph/optimization_model.py", line 107, in __init__
    self.build_bus_constraints(bbt)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/solph/optimization_model.py", line 146, in build_bus_constraints
    assembler.registry[bls](e=None, om=self, block=block)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/solph/optimization_model.py", line 472, in _
    lc.add_bus_balance(om, block)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/solph/linear_constraints.py", line 91, in add_bus_balance
    rule=bus_balance_rule)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/pyomo/core/base/block.py", line 483, in __setattr__
    self.add_component(name, val)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/pyomo/core/base/block.py", line 849, in add_component
    val.construct(data)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/pyomo/core/base/constraint.py", line 733, in construct
    ndx)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/pyomo/core/base/misc.py", line 55, in apply_indexed_rule
    return rule(model, *index)
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/solph/linear_constraints.py", line 87, in bus_balance_rule
    lhs = sum(model.w[i, e, t] for i in I[e])
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/oemof/solph/linear_constraints.py", line 87, in <genexpr>
    lhs = sum(model.w[i, e, t] for i in I[e])
  File "/home/frederik/anaconda3/lib/python3.5/site-packages/pyomo/core/base/indexed_component.py", line 351, in __getitem__
    raise KeyError(msg)
KeyError: "Error accessing indexed component: Index '('transport_bel1_1bel1', 'bel1_1', 2773)' is not valid for array component 'w'"

-----------------------------------------------------------------------
Code:
-----------------------------------------------------------------------
import pandas as pd
from oemof.solph import predefined_objectives as predefined_objectives
from oemof.tools import logger
from oemof.core import energy_system as es
from oemof.core.network.entities import Bus
from oemof.core.network.entities.components import transports as transport

logger.define_logging()

time_index = pd.date_range('1/1/2012', periods=8760, freq='H')
simulation = es.Simulation(timesteps=range(len(time_index)), verbose=True, solver='cbc',
                           objective_options={'function': predefined_objectives.minimize_cost})

sys1 = es.EnergySystem(time_idx=time_index, simulation=simulation)
bel1 = Bus(uid="bel1", type="el", shortage_costs=70, balanced=True, shortage=True)

sys1_1 = es.EnergySystem(time_idx=time_index, simulation=simulation)
bel1_1 = Bus(uid="bel1_1", type="el", shortage_costs=70, balanced=True, shortage=True)

sys1.entities = sys1.entities + sys1_1.entities
sys1.connect(bel1, bel1_1, in_max=10, out_max=10, eta=0.9, transport_class=transport.Simple)

sys1.optimize()

-----------------------------------------------------------------------
Thank you for support!

**Comment by caro-rli** [comment]
I'm not sure if I understand what you are trying to do. But if you want to create two buses and connect them you should do it like this:

```python
import pandas as pd
from oemof.solph import predefined_objectives as predefined_objectives
from oemof.tools import logger
from oemof.core import energy_system as es
from oemof.core.network.entities import Bus
from oemof.core.network.entities.components import transports as transport

import numpy as np

logger.define_logging()

time_index = pd.date_range('1/1/2012', periods=8760, freq='H')
simulation = es.Simulation(timesteps=range(len(time_index)), verbose=True, solver='cbc',
objective_options={'function': predefined_objectives.minimize_cost})

sys1 = es.EnergySystem(time_idx=time_index, simulation=simulation)

bel1 = Bus(uid="bel1", type="el", shortage_costs=70, balanced=True, shortage=True)

bel1_1 = Bus(uid="bel1_1", type="el", shortage_costs=70, balanced=True, shortage=True)

transport_class=transport.Simple(uid='transport',
                                 inputs=[bel1],
                                 outputs=[bel1_1],
                                 in_max=np.ones(8760)*10,
                                 out_max=np.ones(8760)*10,
                                 eta=np.ones(8760)*0.9)

sys1.optimize()
```

But you are missing components like sources and sinks here, so there is nothing to be optimized here.

**Comment by uvchik** [comment]
As discussed in #140 there is a difference between an oemof energysystem and a physical energy system. At the moment it is not intended to create more than one oemof energysytem object but this object can contain more than one isolated energy systems.

The following picture from issue #140 shows two isolated systems that are optionally connect with a power line. 

![issue_140_a](https://cloud.githubusercontent.com/assets/4760584/14524421/84d60636-0238-11e6-88c6-f378e001a814.png)

Be aware that a transport object is directed, so that you have to define two objects to get a bi-directional line.

**Comment by Jazzpilz** [comment]
Thank you for the explanation, this helped quite a lot!

Am 26.05.2016 um 13:57 schrieb ukrien:
