### ISSUE TITLE
Examples do not work anymore

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#173]
With commit d4cfcb04437 the examples (e.g. storage_invest) do not work any more. The problem seems to be caused by a cyclic import. The "oemof/core/energy_system.py" needs the oemof/solph/ groupings", which needs the energy_system of oemog/core. 

I wonder why a core module depends on a solph module?

Here is the error code:

```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/core/energy_system.py", line 21, in <module>
    from oemof.solph.optimization_model import OptimizationModel as OM
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/__init__.py", line 8, in <module>
    from oemof.solph.groupings import GROUPINGS
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/groupings.py", line 20, in <module>
    from oemof.core import energy_system as core_es
ImportError: cannot import name 'energy_system'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof/examples/storage_optimization/storage_invest.py", line 44, in <module>
    from oemof.core import energy_system as core_es
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/core/energy_system.py", line 23, in <module>
    from oemof.solph import OperationalModel as OM
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/__init__.py", line 8, in <module>
    from oemof.solph.groupings import GROUPINGS
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/groupings.py", line 20, in <module>
    from oemof.core import energy_system as core_es
ImportError: cannot import name 'energy_system'

**Comment by uvchik** [comment]
Changing the import according to @simnh's fix does not help to fix the tests.

```diff
- from oemof.core import energy_system as core_es
- self.energysystem = core_es.EnergySystem(groupings=solph.GROUPINGS, time_idx=self.date_time_index)
+ from oemof import core
+ self.energysystem = core.energy_system.EnergySystem(groupings=solph.GROUPINGS, time_idx=self.date_time_index)

```
I use the following command:
```nosetests3 -w "/path/to/my/git_home/oemof" --with-doctest --rednose```

I get the following output:
```python
XX...........XX.......
-----------------------------------------------------------------------------
1) ERROR: Failure: ImportError (cannot import name 'energy_system')

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.4/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.4/imp.py line 235 in load_module
      return load_source(name, filename, file)
    /usr/lib/python3.4/imp.py line 171 in load_source
      module = methods.load()
    <frozen importlib._bootstrap> line 1220 in load
      
    <frozen importlib._bootstrap> line 1200 in _load_unlocked
      
    <frozen importlib._bootstrap> line 1129 in _exec
      
    <frozen importlib._bootstrap> line 1471 in exec_module
      
    <frozen importlib._bootstrap> line 321 in _call_with_frames_removed
      
    oemof/core/energy_system.py line 23 in <module>
      from oemof.solph import OperationalModel as OM
    oemof/solph/__init__.py line 8 in <module>
      from oemof.solph.groupings import GROUPINGS
    oemof/solph/groupings.py line 20 in <module>
      from oemof.core import energy_system as core_es
   ImportError: cannot import name 'energy_system'

-----------------------------------------------------------------------------
2) ERROR: Failure: ImportError (cannot import name 'blocks')

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.4/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.4/imp.py line 245 in load_module
      return load_package(name, filename)
    /usr/lib/python3.4/imp.py line 217 in load_package
      return methods.load()
    <frozen importlib._bootstrap> line 1220 in load
      
    <frozen importlib._bootstrap> line 1200 in _load_unlocked
      
    <frozen importlib._bootstrap> line 1129 in _exec
      
    <frozen importlib._bootstrap> line 1471 in exec_module
      
    <frozen importlib._bootstrap> line 321 in _call_with_frames_removed
      
    oemof/solph/__init__.py line 8 in <module>
      from oemof.solph.groupings import GROUPINGS
    oemof/solph/groupings.py line 23 in <module>
      from . import blocks
   ImportError: cannot import name 'blocks'

-----------------------------------------------------------------------------
3) ERROR: Failure: ImportError (cannot import name 'blocks')

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.4/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.4/imp.py line 235 in load_module
      return load_source(name, filename, file)
    /usr/lib/python3.4/imp.py line 171 in load_source
      module = methods.load()
    <frozen importlib._bootstrap> line 1220 in load
      
    <frozen importlib._bootstrap> line 1200 in _load_unlocked
      
    <frozen importlib._bootstrap> line 1129 in _exec
      
    <frozen importlib._bootstrap> line 1471 in exec_module
      
    <frozen importlib._bootstrap> line 321 in _call_with_frames_removed
      
    tests/constraint_tests.py line 10 in <module>
      from oemof.solph import OperationalModel
    oemof/solph/__init__.py line 8 in <module>
      from oemof.solph.groupings import GROUPINGS
    oemof/solph/groupings.py line 23 in <module>
      from . import blocks
   ImportError: cannot import name 'blocks'

-----------------------------------------------------------------------------
4) ERROR: Failure: ImportError (cannot import name 'blocks')

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.4/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.4/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.4/imp.py line 235 in load_module
      return load_source(name, filename, file)
    /usr/lib/python3.4/imp.py line 171 in load_source
      module = methods.load()
    <frozen importlib._bootstrap> line 1220 in load
      
    <frozen importlib._bootstrap> line 1200 in _load_unlocked
      
    <frozen importlib._bootstrap> line 1129 in _exec
      
    <frozen importlib._bootstrap> line 1471 in exec_module
      
    <frozen importlib._bootstrap> line 321 in _call_with_frames_removed
      
    tests/regression_tests.py line 12 in <module>
      from oemof.solph.optimization_model import OptimizationModel as OM
    oemof/solph/__init__.py line 8 in <module>
      from oemof.solph.groupings import GROUPINGS
    oemof/solph/groupings.py line 23 in <module>
      from . import blocks
   ImportError: cannot import name 'blocks'


-----------------------------------------------------------------------------
22 tests run in 1.5 seconds. 
4 errors (18 tests passed)

```

**Comment by uvchik** [comment]
Worked for a while but a new error occurred with commit 22e55e10cb.

Executing the storage_invest.py:

```python
22:23:33-INFO-Path for logging: /home/uwe/.oemof/log_files
22:23:33-INFO-Used oemof version: f15f63c5@first-refactoring/solph/dev
22:23:33-INFO-Initialize the energy system
22:23:33-INFO-Create oemof objects
22:23:34-INFO-Optimise the energy system
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof/examples/solph/storage_optimization/storage_invest.py", line 234, in <module>
    esys = optimise_storage_size(esys)
  File "/home/uwe/rli-lokal/git_home/oemof/examples/solph/storage_optimization/storage_invest.py", line 130, in optimise_storage_size
    om = OperationalModel(energysystem, timeindex=energysystem.time_idx)
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/plumbing.py", line 204, in __init__
    self.objective_function()
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/plumbing.py", line 217, in objective_function
    expr += block._objective_expression()
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/blocks.py", line 690, in _objective_expression
    for t in m.TIMESTEPS)
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/blocks.py", line 690, in <genexpr>
    for t in m.TIMESTEPS)
AttributeError: 'OperationalModel' object has no attribute 'variable_costs'

Process finished with exit code 1
```

Running the tests:

```python
my@my ~ $ nosetests -w "/path/to/oemof" --with-doctest --rednose --doctest-options '+ELLIPSIS'
...............X.X.XX.X........
-----------------------------------------------------------------------------
1) ERROR: Wrong constraints for fixed source + invest sink w. `summed_max`.

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    tests/constraint_tests.py line 149 in test_fixed_source_invest_sink
      self.compare_lp_files('fixed_source_invest_sink.lp')
    tests/constraint_tests.py line 39 in compare_lp_files
      timeindex=self.energysystem.time_idx)
    oemof/solph/plumbing.py line 204 in __init__
      self.objective_function()
    oemof/solph/plumbing.py line 217 in objective_function
      expr += block._objective_expression()
    oemof/solph/blocks.py line 690 in _objective_expression
      for t in m.TIMESTEPS)
    oemof/solph/blocks.py line 690 in <genexpr>
      for t in m.TIMESTEPS)
   AttributeError: 'OperationalModel' object has no attribute 'variable_costs'

-----------------------------------------------------------------------------
2) ERROR: Constraint test with a fixed sink and a dispatch invest source.

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    tests/constraint_tests.py line 164 in test_invest_source_fixed_sink
      self.compare_lp_files('invest_source_fixed_sink.lp')
    tests/constraint_tests.py line 39 in compare_lp_files
      timeindex=self.energysystem.time_idx)
    oemof/solph/plumbing.py line 204 in __init__
      self.objective_function()
    oemof/solph/plumbing.py line 217 in objective_function
      expr += block._objective_expression()
    oemof/solph/blocks.py line 690 in _objective_expression
      for t in m.TIMESTEPS)
    oemof/solph/blocks.py line 690 in <genexpr>
      for t in m.TIMESTEPS)
   AttributeError: 'OperationalModel' object has no attribute 'variable_costs'

-----------------------------------------------------------------------------
3) ERROR: Constraint test of a LinearTransformer with Investment.

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    tests/constraint_tests.py line 103 in test_linear_transformer_invest
      self.compare_lp_files('linear_transformer_invest.lp')
    tests/constraint_tests.py line 39 in compare_lp_files
      timeindex=self.energysystem.time_idx)
    oemof/solph/plumbing.py line 204 in __init__
      self.objective_function()
    oemof/solph/plumbing.py line 217 in objective_function
      expr += block._objective_expression()
    oemof/solph/blocks.py line 690 in _objective_expression
      for t in m.TIMESTEPS)
    oemof/solph/blocks.py line 690 in <genexpr>
      for t in m.TIMESTEPS)
   AttributeError: 'OperationalModel' object has no attribute 'variable_costs'

-----------------------------------------------------------------------------
4) ERROR: constraint_tests.Constraint_Tests.test_max_source_min_sink

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    tests/constraint_tests.py line 119 in test_max_source_min_sink
      self.compare_lp_files('max_source_min_sink.lp')
    tests/constraint_tests.py line 39 in compare_lp_files
      timeindex=self.energysystem.time_idx)
    oemof/solph/plumbing.py line 204 in __init__
      self.objective_function()
    oemof/solph/plumbing.py line 217 in objective_function
      expr += block._objective_expression()
    oemof/solph/blocks.py line 690 in _objective_expression
      for t in m.TIMESTEPS)
    oemof/solph/blocks.py line 690 in <genexpr>
      for t in m.TIMESTEPS)
   AttributeError: 'OperationalModel' object has no attribute 'variable_costs'

-----------------------------------------------------------------------------
5) ERROR: constraint_tests.Constraint_Tests.test_storage_invest

   Traceback (most recent call last):
    /usr/local/lib/python3.4/dist-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    tests/constraint_tests.py line 203 in test_storage_invest
      self.compare_lp_files('storage_invest.lp')
    tests/constraint_tests.py line 39 in compare_lp_files
      timeindex=self.energysystem.time_idx)
    oemof/solph/plumbing.py line 204 in __init__
      self.objective_function()
    oemof/solph/plumbing.py line 217 in objective_function
      expr += block._objective_expression()
    oemof/solph/blocks.py line 690 in _objective_expression
      for t in m.TIMESTEPS)
    oemof/solph/blocks.py line 690 in <genexpr>
      for t in m.TIMESTEPS)
   AttributeError: 'OperationalModel' object has no attribute 'variable_costs'


-----------------------------------------------------------------------------
31 tests run in 1.4 seconds. 
5 errors (26 tests passed)
```

**Comment by simnh** [comment]
Should work now. But I am not sure. I think we need the variable costs added in InvestmentFlow because investflows do not end up in 'normal' flow block. I hope this is also correct for the StorageInvest class / block

**Comment by simnh** [comment]
Ah now that I see it, the storage does not have variable costs..is this correct? I do not think so.

**Comment by uvchik** [comment]
Variable cost related to what? Level? I think it is right, that there are no variable costs in the storage class.

**Comment by simnh** [comment]
To inflow or/and outflow of storage. I can think of various applications where this might be useful.

**Comment by uvchik** [comment]
But than the variable costs are part of the `Flow` class.

**Comment by simnh** [comment]
Yes, but `fixed_costs` are as well, but still we use a attribute in storage class, because Flow are created "under the hood".

**Comment by uvchik** [comment]
Funny issue for this discussion and @gnn is assigned :smile: So if this comment will not clear the topic we should open a new issue.

The flow are not created "under the hood" and you can define fixed_cost for each flow and for the storage and you can define variable_cost for each flow and ep_costs for the investment:

```python
Storage(
    label='storage',
    inputs={bel: Flow(variable_costs=15, fixed_costs=5)},
    outputs={bel: Flow(variable_costs=13, fixed_costs=3)},
    nominal_input_capacity_ratio=1/6, inflow_conversion_factor=1,
    nominal_output_capacity_ratio=1/6, outflow_conversion_factor=0.8,
    fixed_costs=35, investment=Investment(ep_costs=epc))
```

**Comment by simnh** [comment]
Ah yes of course, stupid me. Ok I was confused be the extra fixed costs, but we provide this to either 
connect fixed_costs with power or capacity. I remember now. I like it!
