### ISSUE TITLE
Allow entities to have non string uids

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#26]
Using the _Two-Region-Example_ with the actual commit (e87fd934) on the two_region_example branch, I get a pyomo-error. I do not know pyomo very good but I checked the entities and could not find anything. Everything seems to be like it was before.

Does anybody has an idea what cases this error?

```python
INFO:root:Processing region: Landkreis Wittenberg (LanWit)
INFO:root:Processing region: Stadt Dessau-Roßlau (StaDes)
ERROR: Constructing component 'w_index_0' from data=None failed:
	ValueError: The value=('bus', 'Landkreis Wittenberg', 'elec', 'sink', 'Landkreis Wittenberg', 'elec') does not have dimension=2, which is needed for set=w_index_0
ERROR:pyomo.core:Constructing component 'w_index_0' from data=None failed:
ValueError: The value=('bus', 'Landkreis Wittenberg', 'elec', 'sink', 'Landkreis Wittenberg', 'elec') does not have dimension=2, which is needed for set=w_index_0
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof_base/examples/development_examples/two_regions_example.py", line 259, in <module>
    TwoRegExample.optimize()
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/core/energy_system.py", line 89, in optimize
    self.optimization_model = OM(energysystem=self)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 89, in __init__
    var.add_continuous(model=self, edges=self.all_edges)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/variables.py", line 79, in add_continuous
    model.w = po.Var(edges, model.timesteps, within=po.NonNegativeReals)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 448, in __setattr__
    self.add_component(name, val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 686, in add_component
    self._add_temporary_set(val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 593, in _add_temporary_set
    val.cname()+"_index_"+str(ctr)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 620, in _construct_temporary_set
    self.add_component(name,obj)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 780, in add_component
    val.construct(data)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/sets.py", line 1197, in construct
    self.add(val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/sets.py", line 746, in add
    self._verify(tmp)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/sets.py", line 699, in _verify
    raise ValueError("The value="+str(element)+" does not have dimension="+str(self.dimen)+", which is needed for set="+self.cname(True))
ValueError: The value=('bus', 'Landkreis Wittenberg', 'elec', 'sink', 'Landkreis Wittenberg', 'elec') does not have dimension=2, which is needed for set=w_index_0
```

**Comment by uvchik** [comment]
I found out, that the error is raised, because I used tuples to define the uid of an object. Using tuples for the uid was the idea of @gnn. Now he will try to fix it. So far I got along with the following lines.

```python
# Converting the uids from tuple to string
for entity in TwoRegExample.entities:
    entity.uid = str(entity.uid)
# Optimize the energy system
TwoRegExample.optimize()
```

**Comment by gnn** [comment]
I'm going to change the title of this issue so that I immediately know what has to be done in order to fix it. For future reference, the old title was "Unknown pyomo error while trying to optimize a simple energy system".

**Comment by uvchik** [comment]
As long as it does not work to use tuples as uid's I can't write a test with tuples as uids and so another problem occurred (see [comment on PR 107](../commit/dd18861b77b3bffe7a0c1023d8edf7b050320ad5#commitcomment-16388875)). Is there chance that this issue will be fixed soon?

**Comment by gnn** [comment]
Sorry for not being able to squash this yet. I asked the pyomo devs during the Aachen workshop though and got some pointers and what is and what is not usable as a pyomo index, so I'm a little bit closer to fixing this. I'll set the milestone to the refactoring meeting, because maybe I'll be able to get enough information about this until then.

**Comment by uvchik** [comment]
@gnn : Thank you for still caring about this :smile:

**Comment by uvchik** [comment]
Outdated with v0.1beta .
