### ISSUE TITLE
How do I add a new bus/component to the results dictionary?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#96]
I added a new bus and a new component to solph. How do I get the results? So far I just get the following error. I added a HeatBus class as a child class of Bus containing temperature attributes. 

See the `features/heatstorage_with_dT` branch for more details. Use this branch with [the example file](../../reegis-hp/blob/master/reegis-hp/example.py) of reegis-hp to get the following error.

```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/reegis-hp/reegis-hp/example.py", line 239, in <module>
    energysystem.optimize()
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/core/energy_system.py", line 137, in optimize
    self.results = om.results()
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/optimization_model.py", line 273, in results
    block = getattr(self, str(type(entity)))
AttributeError: 'OptimizationModel' object has no attribute '<class 'oemof.core.network.entities.buses.HeatBus'>'
```

**Comment by simonhilpert** [comment]
It sounds if there is no 'block' created for the new class. did you write an assembler function and check if the block is created inside solph?

**Comment by uvchik** [comment]
You are right but the assembler structure is very fancy. I would like to use the assembler of the `Bus` class. Is this possible or do I have to create a new assembler that looks exactly the same but starts with `@assembler.register(HeatBus)`?

**Comment by uvchik** [comment]
I tried to add a HeatBus assembler but it doesn't work (see commit 9564be7). First I tried to use the same assembler but no success. Than I tried to group the buses as we group the components. You can see this approach in the commit above. Still no success. Actually I do not like to have the bus assembler twice (Bus, HeatBus) because it is exactly the same. Maybe this causes the following error:
```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/reegis-hp/reegis-hp/example.py", line 239, in <module>
    energysystem.optimize()
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/core/energy_system.py", line 130, in optimize
    om = OM(energysystem=self)
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/optimization_model.py", line 108, in __init__
    self.build_bus_constraints(bbt)
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/optimization_model.py", line 147, in build_bus_constraints
    assembler.registry[bls](e=None, om=self, block=block)
  File "/home/uwe/rli-lokal/git_home/oemof/oemof/solph/optimization_model.py", line 467, in _
    within=po.NonNegativeReals)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 476, in __setattr__
    self.add_component(name, val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 686, in add_component
    self._add_temporary_set(val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 593, in _add_temporary_set
    val.cname()+"_index_"+str(ctr)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 620, in _construct_temporary_set
    self.add_component(name,obj)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 640, in add_component
    % (name, type(val), self.cname(), type(getattr(self, name))))
RuntimeError: Cannot add component 'excess_slack_index_0' (type <class 'pyomo.core.base.sets.SimpleSet'>) to block 'unknown': a component by that name (type <class 'pyomo.core.base.sets.SimpleSet'>) is already defined.
``` 

Can I define a name? 
`block 'unknown': a component by that name (type <class 'pyomo.core.base.sets.SimpleSet'>) is already defined`

@simonhilpert @gnn : Do you see a way to avoid the duplicate assembler? This might also avoid this error.

See #97 for more details.

**Comment by simonhilpert** [comment]
Ok puh:

The error occurs, because the excess / shortage variables are directly added to the optimization model om.excess_slack and not to the bus block om.block.excess_slack.

We had this implemented but changed it- unfortunatly i don know the reason why we did it. 
Actually we talked about adding a slack component which would be inline with the general structure. 

Do you need excess variables? If yes you need to group theses vars inside blocks. Then you will need to adapt: results writing in solph, objective function creation, bus balances. 

I changed this in commit : commit 16290383501a2b6e58e2ac507a72038439d35fd7

I think I did it because of the pyomo_fast_build option....

**Comment by uvchik** [comment]
Yes, reverting this commit works for me. But I guess that means that something else will not work any more.

What shall we do?

**Comment by simonhilpert** [comment]
I think it makes more sense to merge the feature branch from: #104

**Comment by uvchik** [comment]
Merging `features/slack_components` works for me. I will do some plausibility checks now.

**Comment by uvchik** [comment]
It works now but it was quite complicated. I think this is a topic for the restructuring meeting.
